language: node_js
node_js: stable
env:
  global:
   - COMMIT=${TRAVIS_COMMIT::6}

services:
- docker
install:
  - go get -u -v github.com/bmuschko/link-verifier
before_script:
  - link-verifier --dirs docs,website,README.md --fail=false
script:
  - python tag.py
  - cd website
  - yarn install
  - yarn build
  - cd ..
  - 
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=mayadataio/litmus-docs;
     docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$TRAVIS_BRANCH-$COMMIT . && docker push $REPO; 
    fi
  
  - if [ "$TRAVIS_BRANCH" = "staging" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=mayadataio/stage-litmus-docs;
       docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$TRAVIS_BRANCH-$COMMIT . && docker push $REPO; 
    fi
